import { EXECUTOR } from '@/configuration/constants';
import { CONFIG } from '@/configuration';

// Local constants used in this file
export const RELAYER_EVENTS = {
  TRANSACTION_QUEUED: EXECUTOR.EVENTS.TRANSACTION_QUEUED,
  TRANSACTION_CONFIRMED: EXECUTOR.EVENTS.TRANSACTION_CONFIRMED,
  TRANSACTION_FAILED: EXECUTOR.EVENTS.TRANSACTION_FAILED,
  TIPS_TRANSFERRED: EXECUTOR.EVENTS.TIPS_TRANSFERRED,
  ERROR: EXECUTOR.EVENTS.ERROR,
} as const;

export const BASE_EVENTS = {
  TRANSACTION_QUEUED: EXECUTOR.EVENTS.TRANSACTION_QUEUED,
  TRANSACTION_CONFIRMED: EXECUTOR.EVENTS.TRANSACTION_CONFIRMED,
  TRANSACTION_FAILED: EXECUTOR.EVENTS.TRANSACTION_FAILED,
  TIPS_TRANSFERRED: EXECUTOR.EVENTS.TIPS_TRANSFERRED,
  ERROR: EXECUTOR.EVENTS.ERROR,
} as const;

export const RELAYER_QUEUE = {
  PROCESSOR_INTERVAL: EXECUTOR.QUEUE.QUEUE_PROCESSOR_INTERVAL,
  MAX_BATCH_SIZE: EXECUTOR.QUEUE.MAX_BATCH_SIZE,
  MIN_BATCH_SIZE: EXECUTOR.QUEUE.MIN_BATCH_SIZE,
} as const;

export const BASE_QUEUE = {
  PROCESSOR_INTERVAL: EXECUTOR.QUEUE.QUEUE_PROCESSOR_INTERVAL,
  MAX_BATCH_SIZE: EXECUTOR.QUEUE.MAX_BATCH_SIZE,
  MIN_BATCH_SIZE: EXECUTOR.QUEUE.MIN_BATCH_SIZE,
  MAX_RETRIES: EXECUTOR.QUEUE.MAX_RETRIES,
  RETRY_DELAY: EXECUTOR.QUEUE.RETRY_DELAY,
} as const;

export const RELAYER_PROFITABILITY = {
  INCLUDE_GAS_COST: CONFIG.profitability.includeGasCost,
  MIN_PROFIT_MARGIN: CONFIG.profitability.minProfitMargin,
} as const;

export const BASE_PROFITABILITY = {
  INCLUDE_GAS_COST: CONFIG.profitability.includeGasCost,
  MIN_PROFIT_MARGIN: CONFIG.profitability.minProfitMargin,
} as const;
